# Generated by Django 2.1 on 2019-04-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='introtext',
            field=models.TextField(blank=True, verbose_name='Вводный текст'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infoshop.Owner', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_audio',
            field=models.BooleanField(default=False, verbose_name='Слушать'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_book',
            field=models.BooleanField(default=False, verbose_name='Читать'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_flow',
            field=models.BooleanField(default=False, verbose_name='Участвовать'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_video',
            field=models.BooleanField(default=False, verbose_name='Смотреть'),
        ),
        migrations.AlterField(
            model_name='author',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='author',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO описание'),
        ),
        migrations.AlterField(
            model_name='author',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO ключевые слова'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO ключевые слова'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO описание'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO ключевые слова'),
        ),
        migrations.AlterField(
            model_name='school',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='school',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO описание'),
        ),
        migrations.AlterField(
            model_name='school',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO ключевые слова'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'alias')},
        ),
    ]
